### ISSUE TITLE
Telefoonnummer heeft geen validatie.

### ISSUE THREAD

**Issue by ghost** [Let-s-Event-Ontwikkelteam/lets-event#55]
![unknown](https://user-images.githubusercontent.com/31475184/68943620-f5a11c80-07ab-11ea-9e2e-11ea23662ebc.png)

- Ga naar accountinstellingen.
- Verander telefoonnummer naar tekst.

Hier kan je alles in vullen wat je wilt ookal is het geen telefoonnummer.

**Comment by YestinJarrett** [comment]
Opgelost met behulp van Regular Expressions en dit toegepast op telefoonnummer veld.
