### ISSUE TITLE
Je kan overeenkomende toernooien aanmaken.

### ISSUE THREAD

**Issue by ghost** [Let-s-Event-Ontwikkelteam/lets-event#57]
![unknown](https://user-images.githubusercontent.com/31475184/68944284-c7244100-07ad-11ea-93cf-a10848d314ee.png)

- Ga naar toernooien.
- Maak 1 toernooi aan.
- Maak een toernooi aan met dezelfde data.

Hierbij is het onhandig om de juiste toernooi te vinden.

**Comment by FdeRaadt** [comment]
Vanaf nu moet een naam van een toernooi uniek zijn.
beschrijving van een toernooi hoeft niet uniek te zijn.
