### ISSUE TITLE
Password reset werkt niet.

### ISSUE THREAD

**Issue by ghost** [Let-s-Event-Ontwikkelteam/lets-event#58]
- Ga naar loginscherm.
- Klik op wachtwoord vergeten.
- Voer je email in.
- Klik op send password reset link.

Hierdoor krijg je een error dat zegt dat je geauthenticeert moet zijn om het te kunnen aanpassen.

**Comment by YestinJarrett** [comment]
Het versturen van een password reset link heeft nooit gewerkt. Wel kunnen wij werken aan de response die we aan de gebruiker teruggeven op het moment dat een gebruiker op de knop voor het resetten van het wachtwoord klikt.

**Comment by YestinJarrett** [comment]
Wat we hebben gedaan om deze bug op te lossen is om tijdelijk de password reset knop weg te halen omdat we nog niet aan deze feature hebben gewerkt.
Ook zijn we bezig om overal betere feedback aan de gebruiker te tonen op het moment dat er iets fout gaat.
